config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/error', to: 'home#error', as: 'error'
  get '/auth/twitter/callback', to: 'sessions#create', as: 'callback'
  get '/auth/failure', to: 'sessions#error', as: 'failure'
  get '/account', to: 'user#my_timeline', as: 'show'
  get '/signout', to: 'sessions#destroy', as: 'signout'

  resource :user, only: [], path: "" do
    post 'follow(/:username)', to: 'user#follow', as: 'follow'
    post 'unfollow/:username', to: 'user#unfollow', as: 'unfollow'
    post 'tweet(/:tweet)', to: 'user#tweet', as: 'tweet'
    post 'comment/:tweet_id', to: 'user#comment', as: 'comment'
    post 'message(/:username)(/:body)', to: 'user#message', as: 'message'
    get 'my_tweets', to: 'user#my_tweets', as: 'my_tweets'
    get 'friends', to: 'user#friends', as: 'friends'
    get 'friends_timeline', to: 'user#friends_timeline', as: 'friends_timeline'
    get 'single_timeline(/:username)', to: 'user#single_timeline', as: 'single_timeline'
  end
end

app/models/concerns/twitterable.rb
module Twitterable
  
  extend ActiveSupport::Concern

  module ClassMethods
    def flush_client
      @@client = nil
    end
  end

  def client
    @@client ||= Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['CONSUMER_KEY']
      config.consumer_secret = ENV['CONSUMER_SECRET']
      config.access_token = self.oauth_token
      config.access_token_secret = self.oauth_secret
    end
  end

  def user_instance
    @user ||= client.user
  end

  def my_tweets
    def collect_with_max_id(options = {})
      max_id = options[:max_id]
      collection = options[:collection] || []
      no_recursion = options[:no_recursion]
      response = yield(max_id)
      collection += response
      (response.empty? || no_recursion) ? collection.flatten : collect_with_max_id(collection, response.last.id - 1, &block)
    end

    collect_with_max_id({no_recursion: true}) do |max_id|
      options = {count: 20, include_rts: true}
      options[:max_id] = max_id unless max_id.nil?
      client.user_timeline(self, options)
    end
  end

  def home_timeline
    client.home_timeline
  end

  def followers
    client.followers
  end

  def user_timeline(username)
    client.user_timeline(username)
  end

  def tweet(message)
    client.update(message)
  end

  def follow(username)
    client.follow(username)
  end

  def unfollow(username)
    client.unfollow(username)
  end

  def following?(username)
    client.user(username, {include_entities: false}).following?
  end

  def block(username)
    client.block(username)
  end

  def unblock(username)
    client.unblock(username)
  end

  def search
  end

  def message(username, body)
    client.create_direct_message(username, body)
  end

  def statuses_count
    user_instance.statuses_count
  end

  def friends_count
    user_instance.friends_count
  end

  def followers_count
    user_instance.followers_count
  end

  def favorites_count
    user_instance.favorites_count
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  ##This concern can be used to initiate and use methods of Twitter Social client (Singleton pattern applied, to reduce requests to the client)
  include Twitterable
  #--------------Attributes---------------
  alias_attribute :screen_name, :nickname
  #--------------Methods------------------
  
  #**************Public methods***********
  ###############Class Methods############
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid).permit!).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.profile_image_url = auth.info.image
      user.nickname = auth.info.nickname
      user.description = auth.info.description
      user.oauth_token = auth.credentials.token
      user.oauth_secret = auth.credentials.secret
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  helper_method :current_user
  #controller concern for exceptions handling
  include ExceptionHandler

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def client
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['CONSUMER_KEY']
      config.consumer_secret = ENV['CONSUMER_SECRET']
      config.access_token = current_user.oauth_token
      config.access_token_secret = current_user.oauth_secret
    end
  end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from Twitter::Error::TooManyRequests do |ex|
      flash[:error] = t('app.messages.errors.rate_limit_exceeded')
      redirect_to error_url
    end
    rescue_from Twitter::Error::NotFound do |ex|
      flash[:error] = t('app.messages.errors.user_not_found')
      redirect_to error_url
    end
    rescue_from Twitter::Error::RequestTimeout do |ex|
      flash[:error] = t('app.messages.errors.timeout')
      redirect_to error_url
    end

    rescue_from OAuth::Unauthorized do |ex|
      flash[:error] = t('app.messages.errors.auth_required')
      redirect_to error_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def error
    render layout: 'error'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to my_tweets_user_path, notice: 'Signed in sucessfully'
  end
 
  def destroy
    reset_session
    User.flush_client
    redirect_to root_path
  end

  def error
    flash[:error] = 'Sign in to Twitter failed'
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  #core actions
  def my_tweets
	  @tweets = current_user.my_tweets
  end

  def friends_timeline
    @tweets = current_user.home_timeline
    @is_followed = true
  end

  def friends
    @friends = current_user.followers
  end

  def single_timeline
    begin
      @tweets = current_user.user_timeline(@username = user_params[:username])
      @user = client.user(@username)
      @is_followed = current_user.following?(@user)
    rescue Twitter::Error::NotFound
      flash[:error] = t('app.messages.errors.user_not_found', username: @username)
      redirect_to my_tweets_user_path
		end
  end

  def follow
    begin
      current_user.follow(username = user_params[:username])
    rescue Twitter::Error::NotFound
      flash[:error] = t('app.messages.errors.user_not_found', username: username)
    end
    redirect_to friends_timeline_user_path, notice: t('app.messages.followed', username: username)
  end

  def unfollow
    current_user.unfollow(username = user_params[:username])
    redirect_to friends_timeline_user_path, notice: t('app.messages.unfollowed', username: username)
  end

  def tweet
    current_user.tweet(user_params[:tweet])
    redirect_to my_tweets_user_path, notice: t('app.messages.success_tweet')
  end

  def message
    current_user.message(username = user_params[:username], user_params[:body])
    redirect_to friends_timeline_user_path, notice: t('app.messages.sent', username: username)
  end

  private

  def user_params
    params.permit(:username, :body, :tweet)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
  	content_for :title, page_title.to_s
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/error.html.erb
<div>
	<ul>
		<li><%= link_to t('app.messages.back_to_home'), root_url%></li>
	</ul>
</div>

app/views/home/index.html.erb
<div>
	<%if current_user.nil? %>
		<%= render "shared/sign_in_form"%>
	<%else%>
		<%= render "shared/sign_out_form"%>
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TwitterDemo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TwitterDemo</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%- unless current_user.nil?-%>
              <li>
                <%= render "user/card/detailed", :user => current_user %>
                <hr />
                <%= render "shared/user_tweet" %>
                <br />
              </li>
            <%-end-%>
            <%= render "shared/nav_links" %>
          </ul>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <%= render "shared/nav_links" %>
              <hr/>
              <li><%= render "shared/user_search" %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy;codeminator <%= Time.now.year %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TwitterDemo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TwitterDemo</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy;codeminator <%= Time.now.year %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_nav_links.html.erb
<li>
	<%if current_user.nil? %>
		<%= link_to t('app.sign_in'), "/auth/twitter"  %>
	<%else%>
	<%= link_to t('app.sign_out'), signout_path  %>
	<%end%>
</li>
<li><%= link_to t('app.my_tweets'), my_tweets_user_path  %></li>
<li><%= link_to t('app.friends_timeline'), friends_timeline_user_path  %></li>

app/views/shared/_sign_in_form.html.erb
<%= form_tag('/auth/twitter', method: 'get') do%>
 	<div class="controls">
    <%= submit_tag t('app.sign_in'), :class => 'btn btn-primary' %>
  </div>
<%-end-%>

app/views/shared/_sign_out_form.html.erb
<%= form_tag(signout_path, method: 'get') do%>
 	<div class="controls">
    <%= submit_tag t('app.sign_out'), :class => 'btn btn-primary' %>
  </div>
<%-end-%>

app/views/shared/_user_search.html.erb
<%= form_tag(single_timeline_user_path, method: 'get') do%>
	 <%= label_tag :search_user, t('app.search_user'), :class => 'control-label' %>
	 	<div class="controls">
      <%= text_field_tag :username, nil, :class => 'form-control' %>
      <br />
      <%= submit_tag t('app.search'), class: 'btn btn-primary', disabled: true %>
    </div>
<%-end-%>

app/views/shared/_user_tweet.html.erb
 <strong><%= label_tag :say_something, t('app.say_something'), :class => 'control-label' %></strong>
<%= form_tag(tweet_user_path, method: 'post') do%>
	 	<div class="controls">
      <%= text_field_tag :tweet, nil, :class => 'form-control' %>
      <br />
      <%= submit_tag t('app.tweet'), class: 'btn btn-primary', disabled: true %>
    </div>
<%-end-%>

app/views/user/_message.html.erb
<%= modal title: t('app.message'), size: :large, id: "modal_#{user.screen_name}", button: {class: :en} do %>
  <div class="modal-body">
    <%= form_tag(message_user_path, method: 'post') do%>
     <%= label_tag :to, t('app.message_to'), :class => 'control-label' %>
     <span><%= user.screen_name%></span>
      <div class="controls">
        <%= hidden_field_tag :username, user.screen_name %>
        <br />
        <%= text_area_tag :body, nil, :class => 'form-control' %>
        <br />
        <%= submit_tag t('app.message_send'), class: 'btn btn-primary', disabled: true %>
      </div>
    <%-end-%>
  </div>
<% end %>

app/views/user/_stats.html.erb
<div class="userStats">
	<table class="table">
		<thead>
			<tr>
				<th><%= t('app.th.tweets')%></th>
				<th><%= t('app.th.following')%></th>
				<th><%= t('app.th.followers')%></th>
				<th><%= t('app.th.favorites')%></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= number_with_delimiter user.statuses_count %></td>
				<td><%= number_with_delimiter user.friends_count %></td>
				<td><%= number_with_delimiter user.followers_count %></td>
				<td><%= number_with_delimiter user.favorites_count %></td>
			</tr>
		</tbody>
	</table>
</div>

app/views/user/card/_detailed.html.erb
<div>
	<div clsss="userImg">
		<%= image_tag user.profile_image_url%>
	</div>
	<div class="userName">
		<strong><%= user.name %></strong>
		<span><%= user.screen_name %></span>
	</div>
	<%= render "user/stats", user: user%>
	<%-unless (description = user.description).blank?-%>
		<div class="userDesc">
			<span><%= description %></span>
		</div>
	<%-end-%>
</div>

app/views/user/card/_summary.html.erb
<%= link_to(image_tag(user.profile_image_url), user.url.to_s, {target: "_blank"}) %>
<%= link_to user.screen_name, user.url.to_s, {target: "_blank"} %>
<br />
<%if current_user.screen_name != user.screen_name%>
	<ul>
		<%-unless defined?(hide_tweets_link)-%>
			<li><%= link_to t('app.show_tweets'), single_timeline_user_path(username: user.screen_name)%></li>
		<%-end-%>
		<li>	
			<%if @is_followed%>
				<%= link_to t('app.unfollow'), unfollow_user_path(user.screen_name), method: 'post' %>
			<%else%>
				<%= link_to t('app.follow'), follow_user_path(user.screen_name), method: 'post' %>
			<%end%>
		</li>
		<li>
			<%= render "user/message", user: user%>
		</li>
	</ul>
<%end%>

app/views/user/friends.html.erb
<h4><%= t('app.friends') %></h4>
<%@friends.each do |friend|%>
	<div>
		<%= render "user/card/summary", :user => friend, :go_to_tweets_link => true %>
	</div>
<%end%>

app/views/user/friends_timeline.html.erb
<div><%= current_user.name %></div>

<h4><%= t('app.friends_timeline') %></h4>
<%@tweets.each do |tweet|%>
<div>
	<%= render "user/card/summary", :user => tweet.user, :go_to_tweets_link => true%>
</div>
<div><%= tweet.text %></div>
<hr/>
<%end%>

app/views/user/my_tweets.html.erb
<%-content_for :title, t('app.my_tweets')-%>
<h4><%= current_user.name %></h4>
<%@tweets.each do |tweet|%>
<div>
	<%= render "user/card/summary", :user => tweet.user %>
</div>
<div><%= tweet.text %></div>
<hr/>
<%end%>

app/views/user/single_timeline.html.erb
<%= render "user/card/detailed", :user => @user%>
<%-content_for :title, t('app.timeline_for', username: @username)-%>
<%@tweets.each do |tweet|%>
<div>
	<%= render "user/card/summary", :user => @user, hide_tweets_link: true, is_followed: @is_followed%>
</div>
<div><%= tweet.text %></div>
<hr/>
<%end%>